module.exports.names = [
    'Tap Out Gym',
    'Lions MMA',
    'Team Titans Gym',
    'Carlos Boxing Gym',
    'Lennys TKD',
    'Hitmans MMA',
    'Gold Titans Gym',
    'Diegos BJJ',
    'Shamrocks Gym',
    'Team Viper MMA',
    'Tiger Muay Thai',
    'Headhunters Gym',
    'Spark Out MMA',
    'Revolution Gym',
];